language: cpp
os: linux
dist: xenial
cache: bundler

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - travis

addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test' # GCC 7
    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'  # Clang/libclang 7.0
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - gcc-7
    - g++-7
    - clang-7
    - libomp-7-dev
    - libboost1.58-dev
    - liblapack-dev
    - openmpi-bin
    - openmpi-common
    - openmpi-doc
    - libopenmpi-dev
    - libblas-dev
    - libfftw3-dev
    - libgmp-dev
    - hdf5-tools
    - libhdf5-serial-dev
    - python-h5py
    - python-dev
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - python-mpi4py
    - python-mako
    - python-sphinx
    - libclang-7-dev
    - python-clang-7
    - libjs-mathjax

before_install:
  - |
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                             --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - |
    sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 60\
                             --slave /usr/bin/clang++ clang++ /usr/bin/clang++-7

install: true

before_script:
  # Stop on first error
  - set -e

  # Build and install TRIQS
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/TRIQS/triqs.git triqs
  - pushd triqs && git checkout 2.2.x && popd
  - mkdir installed
  - mkdir triqs.build && pushd triqs.build
  - |
    CMAKE_OPTS="                                                               \
      -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../installed                    \
      -DCMAKE_BUILD_TYPE=Debug                                                 \
      -DCMAKE_C_COMPILER=/usr/bin/${CC}                                        \
      -DCMAKE_CXX_COMPILER=/usr/bin/${CXX}                                     \
      -DPYTHON_INTERPRETER=/usr/bin/python                                     \
    "
  # Build documentation only when compiling with clang
  - |
    if [[ $CC == "clang" ]]; then
      CMAKE_OPTS="${CMAKE_OPTS}                                                \
        -DLIBCLANG_LOCATION=/usr/lib/x86_64-linux-gnu/libclang-7.so.1          \
        -DMATHJAX_PATH=/usr/share/javascript/mathjax                           \
        -DBuild_Documentation=ON                                               \
      "
    else
      CMAKE_OPTS="${CMAKE_OPTS} -DBuild_Documentation=OFF"
    fi
  - cmake ../triqs ${CMAKE_OPTS}
  - make -j3
  - make install
  - popd

script:
  # Build SOM
  - source $TRAVIS_BUILD_DIR/../installed/share/triqsvars.sh
  - mkdir som.build && pushd som.build
  - |
    CMAKE_OPTS="                                                               \
      -DCMAKE_BUILD_TYPE=Debug                                                 \
      -DCMAKE_C_COMPILER=/usr/bin/${CC}                                        \
      -DCMAKE_CXX_COMPILER=/usr/bin/${CXX}                                     \
    "
  # Build documentation only when compiling with clang
  - |
    if [[ $CC == "clang" ]]; then
      CMAKE_OPTS="${CMAKE_OPTS}                                                \
        -DTRIQS_INVENTORY_DIR=https://triqs.github.io/triqs/2.2.x/             \
        -DBuild_Documentation=ON                                               \
      "
    else
      CMAKE_OPTS="${CMAKE_OPTS} -DBuild_Documentation=OFF"
    fi
  - cmake ../som ${CMAKE_OPTS}
  - make -j3
  - make test
  - make install
  # Prepare docs for deployment
  - |
    if [[ $CC == "clang" ]]; then
      cd $TRAVIS_BUILD_DIR/../som.build
      find doc/html -name "*.html"                                             \
       -type f                                                                 \
       -exec sed -i 's/\/usr\/share\/javascript\/mathjax/\/som\/mathjax/g' {} \;
      cp -r /usr/share/javascript/mathjax doc/html/mathjax
      touch doc/html/.nojekyll
    fi

deploy:
  # Publish documentation
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: false
  local_dir: $TRAVIS_BUILD_DIR/../som.build/doc/html
  on:
    branch: master
    condition: "$CC = clang"
